# Programming Fundamentals

* Data types
    * Integers
    * Floats
    * Strings
    * Lists
    * Dictionaries
    * Booleans
    * Tuples 
    * Sets
    * Arrays
    * Matricies
    * Data frames
* Comparison Operators
* Logical Operators
* if, elif, else statements
* for loops
* while loops
* functions
____

*This worksheet is heavily inspired by Pierian Data's Python course on Udemy.*

In [6]:
# libraries
import numpy as np
import pandas as pd

## Data types

### integers

In [30]:
four = 2 + 2
print(four)

4


In [29]:
type(four)

int

### floats
numbers with decimals

In [32]:
flo = 2.5 - 1.7
print(flo)

0.8


In [33]:
type(flo)

float

### strings

In [22]:
# can use single or double quotes
hi = "Hello world"
print(hi)

Hello world


In [34]:
type(hi)

str

In [23]:
numString = "12345"
print(numString)

12345


In [35]:
type(numString)

str

### lists

can take in basically any data type

In [46]:
[1,2,3]

[1, 2, 3]

In [27]:
# can combine data types
# here we have string, integer, and another list
['hi',1,[1,2]]

['hi', 1, [1, 2]]

In [47]:
my_list = ['a','b','c']

In [38]:
# lists are sequences with a defined order, which means we can index them
my_list[0]

'a'

In [33]:
my_list[1:]

['b', 'c', 'd']

In [49]:
# you can change items through indexing
my_list[0] = "new"
print(my_list)

['new', 'b', 'c']


### dictionaries

key-value pairs.

In [44]:
d = {'key1':'value1','key2':'value2'}

In [40]:
d

{'key1': 'item1', 'key2': 'item2'}

In [41]:
# disctionaries are not ordered, so they can't be indexed like lists
d[0]

KeyError: 0

In [42]:
# have to first use the key name
d['key1']

'item1'

In [45]:
# then could index off of there
d['key1'][0]

'v'

### booleans

true/false.

In [40]:
True

True

In [41]:
False

False

### tuples 

similar to lists, except they are "immutable": you can't reassign items.

In [42]:
t = (1,2,3)

In [43]:
t[0]

1

In [44]:
t[0] = 'NEW'

TypeError: 'tuple' object does not support item assignment

### sets

defined by only unique elements.

In [45]:
{1,2,3}

{1, 2, 3}

In [46]:
{1,2,3,1,2,1,2,3,3,3,3,2,2,2,1,1,2}

{1, 2, 3}

### arrays

one-dimensional vectors.

In [3]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### matricies
two-dimensional matrix. Can also be referred to as an array in Python.

In [50]:
my_mat = [[1,2,3], [4,5,6],[7,8,9]]

In [51]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### data frames

basically a "spreadsheet". Two-dimensional. Key is that they can have different data types. 

In [52]:
data = {'Name':['Tom', 'Nick', 'Sally', 'Joe'],
        'Age':[20, 21, 19, 18]}

df = pd.DataFrame(data)

print(df)

   Age   Name
0   20    Tom
1   21   Nick
2   19  Sally
3   18    Joe


## Comparison Operators

In [47]:
1 > 2

False

In [48]:
1 < 2

True

In [49]:
1 >= 1

True

In [50]:
1 <= 4

True

In [51]:
1 == 1

True

In [52]:
'hi' == 'bye'

False

## Logical Operators

In [53]:
(1 > 2) and (2 < 3)

False

In [54]:
(1 > 2) or (2 < 3)

True

In [1]:
(1 == 2) or (2 == 3) or (4 == 2)

False

## if, elif, else statements

In [56]:
if 1 < 2:
    print('Yep!')

Yep!


In [58]:
if 1 < 2:
    print('first')
else:
    print('last')

first


In [60]:
if 1 == 2:
    print('first')
elif 3 == 3:
    print('middle')
else:
    print('last')

middle


## for loops

In [10]:
nums = [1,2,3,4,5]

In [62]:
for item in nums:
    print(item)

1
2
3
4
5


In [63]:
for item in nums:
    print('Yep')

Yep
Yep
Yep
Yep
Yep


In [12]:
# can use whatever word to iterate over
for cake in nums:
    print(cake + cake)

2
4
6
8
10


## while loops

In [65]:
i = 1
while i < 5:
    print('i is: {}'.format(i))
    i = i + 1

i is: 1
i is: 2
i is: 3
i is: 4


## functions

In [53]:
def square(x):
    return x**2

In [54]:
square(2)

4

In [59]:
def greeting(name):
    print('Hi %s' %(name))

In [60]:
greeting('dude')

Hi dude


In [2]:
def addNum(num1, num2):
    print(num1 + num2)

In [3]:
addNum(5, 10)

15


In [61]:
# here's a function that returns the lesser of two given numbers 
# if both numbers are even
# but returns the greater if one or both numbers are odd
# for example: lesser_of_two_evens(2, 4) would return 2
#              lesser_of_two_evens(2, 5) would return 5
    
def lesser_of_two_evens(a, b):
    if a % 2 == 0 and b % 2 == 0:
        return min(a,b)
    else:
        return max(a,b)

In [62]:
lesser_of_two_evens(2, 4)

2

In [63]:
lesser_of_two_evens(2, 5)

5

## Exercises

Now we’re going to practice a bit! Here are some tasks:
1. Write a script that prints “Hello” if the variable X is equal to 1
2. Write a script that prints “Even Number” if the variable X is an even number, otherwise prints “Not Even”
3. White a script that prints the numbers 1 through 10 using a for loop.
4. White a script that prints the numbers 1 through 10 using a while loop.
5. Create a function that takes in a name as a string argument, and prints out “Hello name”
6. Create a function that will return the product of two integers.
7. Challenge one: Create a function that will return True if an input integer is prime. Otherwise, return False.

#1

In [4]:
x = 1

if x == 1:
    print("Hello")

#2

In [11]:
x = 11

if x % 2 == 0:
    print("Even number")
else:
    print("Odd number")

Odd number


#3

In [20]:
for x in range(1, 11):
        print(x)

1
2
3
4
5
6
7
8
9
10


#4

In [23]:
x = 1

while x < 11:
    print(x)
    x = x + 1

1
2
3
4
5
6
7
8
9
10


#5

In [24]:
def helloYou(name):
    print('Hello %s' %(name))
    
helloYou("Jerry")

Hello Jerry


#6

In [26]:
def prod(num1, num2):
    return num1 * num2

prod(3, 4)

12

#7

In [30]:
def primeCheck(num):
    if (num == 1):
        return False
    elif (num == 2):
        return True
    else:
        for x in range(2, num):
            if(num % x == 0):
                return False
        return True   
    
primeCheck(2)

False